//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touri_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expertise
    {
        public Expertise()
        {
            this.GuideExpertises = new HashSet<GuideExpertises>();
        }
    
        public int expertiseId { get; set; }
        public string expertise1 { get; set; }
        public string description { get; set; }
        public Nullable<int> imageId { get; set; }
    
        public virtual ICollection<GuideExpertises> GuideExpertises { get; set; }
    }
}
