//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touri_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuideProfile
    {
        public GuideProfile()
        {
            this.GuideExpertises = new HashSet<GuideExpertises>();
            this.GuideLanguages = new HashSet<GuideLanguage>();
            this.GuideLocations = new HashSet<GuideLocation>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int guideId { get; set; }
        public string username { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string description { get; set; }
        public int profileImage { get; set; }
    
        public virtual ICollection<GuideExpertises> GuideExpertises { get; set; }
        public virtual ICollection<GuideLanguage> GuideLanguages { get; set; }
        public virtual ICollection<GuideLocation> GuideLocations { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual TouriImage TouriImage { get; set; }
    }
}
