//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touri_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuideExpertis
    {
        public int id { get; set; }
        public int guideId { get; set; }
        public int expertiseId { get; set; }
    
        public virtual Expertise Expertise { get; set; }
        public virtual GuideProfile GuideProfile { get; set; }
    }
}
