//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touri_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.GuideLanguages = new HashSet<GuideLanguage>();
        }
    
        public int LanguageId { get; set; }
        public string Language1 { get; set; }
    
        public virtual ICollection<GuideLanguage> GuideLanguages { get; set; }
    }
}
