//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touri_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public string toUser { get; set; }
        public string fromUser { get; set; }
        public string message1 { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Downloaded { get; set; }
        public Nullable<System.DateTime> LastDownloaded { get; set; }
    }
}
