//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touri_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewedAttribute
    {
        public int ReviewId { get; set; }
        public int AttributeId { get; set; }
        public int Rating { get; set; }
        public string ReviewComments { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Review Review { get; set; }
    }
}
