//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touri_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public int GuideId { get; set; }
        public int TravellerId { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public System.DateTime GuideExperienceDate { get; set; }
        public string ReviewComments { get; set; }
    
        public virtual GuideProfile GuideProfile { get; set; }
        public virtual ReviewedAttribute ReviewedAttribute { get; set; }
    }
}
