//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touri_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouriImage
    {
        public TouriImage()
        {
            this.GuideProfiles = new HashSet<GuideProfile>();
        }
    
        public int id { get; set; }
        public string filename { get; set; }
        public string extension { get; set; }
        public string path { get; set; }
        public string username { get; set; }
        public System.DateTime dateuploaded { get; set; }
        public string category { get; set; }
    
        public virtual ICollection<GuideProfile> GuideProfiles { get; set; }
    }
}
